[KeyOptions]
Keys = None,UserKey,LCKey

[Scripts]
#name of each python scripts
# requirements: 
#    1, class name is upper case of script name
#    2, class takes modules and filename as parameter, those parameters will be given by GUI
#    3,  class has run function for the code generation
C_Scripts = gen_header, gen_svd
Test_Scripts = gen_test_header
Doc_Scripts = gen_ds
#Design_Scripts = gen_verilog_bus
Design_Scripts = gen_mmr_APB,gen_parm_addr,gen_uvm_reg_model
#Design_Scripts = gen_mmr_APB,gen_uvm_reg_model,gen_scan_handler,gen_verilog_instance,gen_non_trim_mmr
DV_Scripts = gen_verilog_bus
